### ISSUE TITLE
Problems with appServer example app

### ISSUE THREAD

**Issue by andysylvester** [scripting/appServer#1]
What I did:
* Copied the example files to my server
* Ran npm install
* Ran node app.js

What I expected to see:
* Sample app running

What actually happened:
* Got an error saying that daveappserver.js could not be found

Next, I reviewed app.js and decided to change line 1 as follows:
FROM:
const daveappserver = require ("./lib/daveappserver.js"); 
TO:
const daveappserver = require ("daveappserver"); 

What I did then:
* Ran node app.js

What I saw:
* My app was running in the terminal window
* Was able to see http://fedwiki.andysylvester.com:1229/ running in a browser

I was able to execute menu commands, but when I tried to sign on to Twitter, I got this URL in response:

http://fedwiki.andysylvester.com:1229/connect?redirect_url=http%3A%2F%2Ffedwiki.andysylvester.com%3A1229%2F

The following response appeared in the browser:

<?xml version='1.0' encoding='UTF-8'?><errors><error code="417">Desktop applications only support the oauth_callback value 'oob'</error></errors>

The following is my config.json file (with dummy Twitter keys)

{
	"productName": "testDaveAppserver",
	"productNameForDisplay": "Example App",

	"urlServerHomePageSource": "http://scripting.com/code/daveappserver/example/index.html",

	"prefsPath": "prefs.json",
	"docsPath": "myDocs/",

	"port": 1229,
	"flWebsocketEnabled": true,
	"websocketPort": 1230,

	"myDomain": "fedwiki.andysylvester.com:1229",

	"twitterConsumerKey": "test1",
	"twitterConsumerSecret": "test2"
	}

**Comment by scripting** [comment]
@andysylvester -- thanks for the report. I fixed the problem with the require statement in the example app.

https://github.com/scripting/appServer/blob/main/README.md#v0532----92621-by-dw

The other issue you report is an issue re registering with Twitter, and I'm not in a position to support Twitter's developer program. 

Also check out the Change Notes outline for today, for a [note](http://drummer.scripting.com/?url=http://drummer.scripting.com/davewiner/drummer/changeNotes.opml&cursor=1632674737000) about appServer. 

Dave
