### ISSUE TITLE
Possible improvements to function httpFullRequest

### ISSUE THREAD

**Issue by scotthansonde** [scripting/appServer#2]
When debugging [http.client on Drummer](https://github.com/scripting/drummerRFC/issues/6) with a local instance of appServer I noticed a couple of possible improvements to the httpFullRequest function in appserver.js.

- My failed call to the GitHub API returned an error message, but I wasn't able to see it in Drummer. It would have been helpful to include `data`in the errstruct at line 109
```
const errstruct = {
  message: "Can't read the URL, \"" + theRequest.url + "\" because we received a status code of " + response.statusCode + ".",
  statusCode: response.statusCode,
  data: data
};
```
- The function is successful only if the returned status code is 200 (line 108). The API I called returned code 204 (No Content) on success, so it'd be nice if the function were successful on any [successful response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses).

**Comment by scripting** [comment]
@papascott -- I've made both these changes in appServer. Not deployed yet. 


```
function httpFullRequest (jsontext, callback) { //11/5/21 by DW
	var theRequest;
	function isErrorStatusCode (theCode) { //11/8/21 by DW
		return ((theCode < 200) || (theCode > 299));
		}
	try {
		theRequest = JSON.parse (jsontext);
		}
	catch (err) {
		callback (err);
		return;
		}
	request (theRequest, function (err, response, data) {
		if (err) {
			callback (err);
			}
		else {
			if (isErrorStatusCode (response.statusCode)) { //11/8/21 by DW
				const errstruct = {
					message: "Can't read the URL, \"" + theRequest.url + "\" because we received a status code of " + response.statusCode + ".",
					statusCode: response.statusCode,
					data //11/8/21 by DW
					};
				callback (errstruct);
				}
			else {
				callback (undefined, data);
				}
			}
		});
	}

```

**Comment by scripting** [comment]
The new version is deployed, and the repo has been updated.

https://github.com/scripting/appServer/blob/main/appserver.js#L94

**Comment by scotthansonde** [comment]
I tried out the deployed version in Drummer, my original script (not setting a User-Agent) worked , returning Status 204.
